defmodule AshCredo.Check.Design.MissingCodeInterface do
  use Credo.Check,
    base_priority: :low,
    category: :design,
    tags: [:ash],
    param_defaults: [excluded_actions: []],
    explanations: [
      check: """
      Resources with actions but no `code_interface` block miss out on Ash's
      generated typed functions. This check inspects each resource's fully
      resolved action list via `Ash.Resource.Info.actions/1` and, for every
      action that has neither a resource-level nor a domain-level code
      interface targeting it, emits a dedicated issue naming the missing
      action.

          # Flagged - action `:published` has no interface anywhere
          actions do
            read :published
          end

          # Preferred - one of:
          code_interface do
            define :published
          end
          # ...or on the domain:
          resources do
            resource MyApp.Post do
              define :published
            end
          end

      ## Requirements

      Your project must be compiled before running `mix credo`. If Ash is
      not available in the VM running Credo, the check is a no-op and emits
      a single diagnostic.

      ## Notes

      Embedded resources are skipped by this check, since they typically
      do not need a code interface.

      ## Configuration

      Specific actions can be suppressed via the `excluded_actions` param,
      which takes a flat list of `"Module.action_name"` strings. Each entry
      is matched literally against the action's fully qualified name (the
      module as returned by `inspect/1`, joined to the action name by a
      dot). Useful for skipping actions generated by extensions such as
      `AshAuthentication` that are not meant to be called via a code
      interface.

          {AshCredo.Check.Design.MissingCodeInterface,
           excluded_actions: [
             "MyApp.Accounts.User.sign_in_with_password",
             "MyApp.Accounts.Token.expunge_expired"
           ]}
      """,
      params: [
        excluded_actions: "List of \"Module.action_name\" strings to skip."
      ]
    ]

  alias AshCredo.Introspection
  alias AshCredo.Introspection.Compiled, as: CompiledIntrospection
  alias AshCredo.Introspection.ResourceContext

  @impl true
  def run(%SourceFile{} = source_file, params) do
    issue_meta = IssueMeta.for(source_file, params)

    CompiledIntrospection.with_compiled_check(
      fn ->
        format_issue(issue_meta,
          message:
            "Ash is not loaded in the VM running Credo - `MissingCodeInterface` is a no-op. Add `:ash` as a dependency, or disable this check in `.credo.exs`.",
          line_no: 1
        )
      end,
      fn ->
        excluded_actions = Params.get(params, :excluded_actions, __MODULE__)

        source_file
        |> Introspection.resource_contexts()
        |> Enum.flat_map(&check_resource(&1, issue_meta, excluded_actions))
      end
    )
  end

  defp check_resource(%ResourceContext{absolute_segments: nil}, _issue_meta, _excluded_actions),
    do: []

  defp check_resource(
         %ResourceContext{absolute_segments: segments, module_ast: module_ast} = context,
         issue_meta,
         excluded_actions
       ) do
    if Introspection.embedded_resource?(context) do
      []
    else
      resource = Module.concat(segments)
      inspect_resource(resource, module_ast, context, issue_meta, excluded_actions)
    end
  end

  defp inspect_resource(resource, module_ast, context, issue_meta, excluded_actions) do
    case CompiledIntrospection.inspect_module(resource) do
      {:ok, info} ->
        flag_missing_interfaces(resource, info, module_ast, context, issue_meta, excluded_actions)

      {:error, :not_loadable} ->
        CompiledIntrospection.with_unique_not_loadable(resource, fn ->
          not_loadable_issue(resource, context, issue_meta)
        end)

      {:error, _} ->
        []
    end
  end

  defp flag_missing_interfaces(
         resource,
         %{actions: actions, interfaces: interfaces, domain: resource_domain},
         module_ast,
         context,
         issue_meta,
         excluded_actions
       ) do
    actions_line = actions_section_line(module_ast, context)

    actions
    |> Enum.reject(fn action ->
      action_has_interface?(action, interfaces, resource_domain, resource) or
        action_excluded?(action, resource, excluded_actions)
    end)
    |> Enum.map(&missing_interface_issue(&1, resource, actions_line, issue_meta))
  end

  defp action_excluded?(action, resource, excluded_actions) do
    "#{inspect(resource)}.#{action.name}" in excluded_actions
  end

  defp action_has_interface?(action, interfaces, resource_domain, resource) do
    not is_nil(CompiledIntrospection.find_interface(interfaces, action.name)) or
      not is_nil(CompiledIntrospection.domain_interface(resource_domain, resource, action.name))
  end

  defp missing_interface_issue(action, resource, line, issue_meta) do
    format_issue(issue_meta,
      message:
        "Action `:#{action.name}` on `#{inspect(resource)}` has no code interface. " <>
          "Define one with `define :#{action.name}` in the resource's `code_interface` block, " <>
          "or `define :some_name, action: :#{action.name}` in the domain's `resource` reference.",
      trigger: "#{action.name}",
      line_no: line
    )
  end

  defp actions_section_line(module_ast, context) do
    actions_ast = Introspection.find_dsl_section(module_ast, :actions)

    Introspection.section_issue_line(actions_ast, Map.get(context, :use_line), 1)
  end

  defp not_loadable_issue(resource, context, issue_meta) do
    format_issue(issue_meta,
      message:
        "Could not load `#{inspect(resource)}` for `MissingCodeInterface`. Run `mix compile` before `mix credo`, or disable this check in `.credo.exs`.",
      line_no: Map.get(context, :use_line) || 1
    )
  end
end
